---
apiVersion: v2
name: vault
description: Vault Deployment
type: application
version: 1.0.1
appVersion: "1.0"
dependencies:
  - name: vault
    version: 0.18.0
    repository: https://helm.releases.hashicorp.com
