---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root
spec:
  project: default
  source:
    repoURL: https://github.com/jonnobrow/minikube-argo-gitops.git
    targetRevision: HEAD
    path: apps/
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
