---
# This level is the chart name
argo-cd:
  # This level maps to the top level of values.yaml in the chart repo
  global:
    image:
      tag: v2.12.5
  # dex is for authentication
  dex:
    enabled: false
  server:
    extraArgs:
      - --insecure
  configs:
    # This would be needed to access private repositories
    # credentialTemplates:
    #   github-1:
    #     url: https://github.com/org/repo-name.git
    #     username: ...
    #     password: ...
    repositories:
      helm:
        type: helm
        name: stable
        url: https://charts.helm.sh/stable
      argocd:
        type: helm
        name: argo-cd
        url: https://argoproj.github.io/argo-helm
