apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: petstore-api
  name: petstore-api
spec:
  ports:
    - name: 80-8080
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: petstore-api
  type: ClusterIP
status:
  loadBalancer: {}
